# Generated by Django 2.0.2 on 2018-02-05 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.SmallIntegerField(choices=[(1, 'homer'), (2, 'plato'), (3, 'jarvis'), (4, 'friday')], default=1)),
                ('start_time', models.DateTimeField(help_text='Please Enter the start time of the meeting')),
                ('end_time', models.DateTimeField(help_text='Enter the End time of the meeting')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('anon_status', models.SmallIntegerField(choices=[(1, 'yes'), (2, 'no')], default=2)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueAns.Meetings')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisf_status', models.BooleanField(choices=[(1, 'yes'), (2, 'no')], default=1)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueAns.Question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'up'), (2, 'dn'), (3, 'n')], default=3)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QueAns.Question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
