# Generated by Django 2.0.2 on 2018-02-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='moderator',
            new_name='asker',
        ),
        migrations.AlterField(
            model_name='meetings',
            name='end_time',
            field=models.DateTimeField(help_text='End time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='start_time',
            field=models.DateTimeField(help_text='Start time of the meeting'),
        ),
    ]
