# Generated by Django 2.0.2 on 2018-02-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0002_auto_20180205_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetings',
            options={'permissions': (('read_item', 'Can read item'),)},
        ),
    ]
