# Generated by Django 2.0.2 on 2018-02-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0003_auto_20180205_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetings',
            options={},
        ),
    ]
