# Generated by Django 2.0.2 on 2018-02-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueAns', '0004_auto_20180206_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (2, 'Downvote'), (3, 'None')], default=3),
        ),
    ]
