# Generated by Django 2.0.2 on 2018-02-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meetings',
            fields=[
                ('meeting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('venue', models.CharField(max_length=50)),
                ('moderator_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=100)),
                ('anon_status', models.CharField(max_length=3)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.meetings')),
            ],
        ),
        migrations.CreateModel(
            name='satisfaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisf_status', models.CharField(max_length=5)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.question')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=1)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.user')),
            ],
        ),
        migrations.AddField(
            model_name='satisfaction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.user'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.user'),
        ),
    ]
